{
  "totalNumberSkippingTests": 8,
  "step-durations": {
    "CheckoutBuild": 0,
    "": 0,
    "ComputeClasspath": 2,
    "CloneRepository": 11,
    "ResolveDependency": 24,
    "TestProject": 47,
    "BuildProject": 19,
    "PushIncriminatedBuild": 5,
    "ComputeSourceDir": 0,
    "SquashRepository": 4
  },
  "nbLibraries": 43,
  "workspace": "./workspace",
  "totalNumberErroringTests": 619,
  "repo": "nutzam/nutz",
  "bugCommit": "https://github.com/nutzam/nutz/compare/4466b64016ca...59623ce76fcb",
  "failingModule": "/root/workspace/nutzam/nutz/220207335",
  "buildid": 220207335,
  "totalNumberFailingTests": 2,
  "error-types": [
    "java.lang.AssertionError",
    "org.nutz.ioc.IocException",
    "java.lang.RuntimeException",
    "java.lang.NullPointerException:"
  ],
  "totalNumberRunningTests": 2244,
  "failing-test-cases": [
    {
      "className": "org.nutz.trans.TransLevelTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.trans.TransLevelTest#testSerializable",
        "org.nutz.trans.TransLevelTest#testReadCommitted",
        "org.nutz.trans.TransLevelTest#testTransLevel"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.RuntimeException",
          "failureDetail": "nutz-test.properties Not FOUND!!! tmpl.nutz-test.properties is a example.",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 6
    },
    {
      "className": "org.nutz.dao.test.normal.EachTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.EachTest#each_by_loop",
        "org.nutz.dao.test.normal.EachTest#query_records",
        "org.nutz.dao.test.normal.EachTest#each_by_like_ignorecase",
        "org.nutz.dao.test.normal.EachTest#each_by_map_namekeyset",
        "org.nutz.dao.test.normal.EachTest#each_by_int_range",
        "org.nutz.dao.test.normal.EachTest#each_by_long_range",
        "org.nutz.dao.test.normal.EachTest#query_records_pager",
        "org.nutz.dao.test.normal.EachTest#each_by_like",
        "org.nutz.dao.test.normal.EachTest#each_by_map_idkeyset",
        "org.nutz.dao.test.normal.EachTest#each_by_pager",
        "org.nutz.dao.test.normal.EachTest#each_by_special_char",
        "org.nutz.dao.test.normal.EachTest#each_by_orderbyset",
        "org.nutz.dao.test.normal.EachTest#each_by_special_char2"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 26
    },
    {
      "className": "org.nutz.dao.texp.CndTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.texp.CndTest#test_other_op",
        "org.nutz.dao.texp.CndTest#test_in_by_str_array",
        "org.nutz.dao.texp.CndTest#test_bracket",
        "org.nutz.dao.texp.CndTest#test_add_other_or_method_by_github_issuse_148",
        "org.nutz.dao.texp.CndTest#test_order",
        "org.nutz.dao.texp.CndTest#test_is_null",
        "org.nutz.dao.texp.CndTest#test_in_by_int_array",
        "org.nutz.dao.texp.CndTest#test_segment",
        "org.nutz.dao.texp.CndTest#test_not_in",
        "org.nutz.dao.texp.CndTest#test_from_obj",
        "org.nutz.dao.texp.CndTest#test_obj_read_write",
        "org.nutz.dao.texp.CndTest#test_is_not_null",
        "org.nutz.dao.texp.CndTest#test_not_sql_group",
        "org.nutz.dao.texp.CndTest#test_in_by_str_list",
        "org.nutz.dao.texp.CndTest#test_equel",
        "org.nutz.dao.texp.CndTest#test_like_in",
        "org.nutz.dao.texp.CndTest#test_gt_like",
        "org.nutz.dao.texp.CndTest#test_in_by_int_list"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 36
    },
    {
      "className": "org.nutz.dao.test.smoke.TableNameTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.smoke.TableNameTest#test_insert_DPet"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.dao.test.exec.SimpleDaoExecTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.exec.SimpleDaoExecTest#test_simple_mysql_exec2",
        "org.nutz.dao.test.exec.SimpleDaoExecTest#test_simple_h2_call",
        "org.nutz.dao.test.exec.SimpleDaoExecTest#test_exec_out",
        "org.nutz.dao.test.exec.SimpleDaoExecTest#test_simple_mysql_exec"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 8
    },
    {
      "className": "org.nutz.dao.test.mapping.DynamicManyTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.mapping.DynamicManyTest#delete_links_partly",
        "org.nutz.dao.test.mapping.DynamicManyTest#delete_with_partly",
        "org.nutz.dao.test.mapping.DynamicManyTest#delete_null_field_links",
        "org.nutz.dao.test.mapping.DynamicManyTest#delete_with",
        "org.nutz.dao.test.mapping.DynamicManyTest#clear_links",
        "org.nutz.dao.test.mapping.DynamicManyTest#update_links",
        "org.nutz.dao.test.mapping.DynamicManyTest#fetch_null_field_links",
        "org.nutz.dao.test.mapping.DynamicManyTest#delete_links",
        "org.nutz.dao.test.mapping.DynamicManyTest#delete_null_field_links_partly",
        "org.nutz.dao.test.mapping.DynamicManyTest#update_with",
        "org.nutz.dao.test.mapping.DynamicManyTest#clear_null_field_links"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 44
    },
    {
      "className": "org.nutz.dao.test.normal.BinaryDaoTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.BinaryDaoTest#test_blob",
        "org.nutz.dao.test.normal.BinaryDaoTest#test_simple_byte_array",
        "org.nutz.dao.test.normal.BinaryDaoTest#test_big_blob",
        "org.nutz.dao.test.normal.BinaryDaoTest#test_clob"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 8
    },
    {
      "className": "org.nutz.dao.test.mapping.DynamicOneTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.mapping.DynamicOneTest#delete_with",
        "org.nutz.dao.test.mapping.DynamicOneTest#fetch_links",
        "org.nutz.dao.test.mapping.DynamicOneTest#delete_links",
        "org.nutz.dao.test.mapping.DynamicOneTest#update_links",
        "org.nutz.dao.test.mapping.DynamicOneTest#update_with",
        "org.nutz.dao.test.mapping.DynamicOneTest#clear_links"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 24
    },
    {
      "className": "org.nutz.dao.test.normal.FieldFilterTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.FieldFilterTest#test_query_by_filter",
        "org.nutz.dao.test.normal.FieldFilterTest#test_insert_by_filter",
        "org.nutz.dao.test.normal.FieldFilterTest#test_update_by_filter",
        "org.nutz.dao.test.normal.FieldFilterTest#test_filter_no_field_match",
        "org.nutz.dao.test.normal.FieldFilterTest#test_select_by_filter"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 10
    },
    {
      "className": "org.nutz.dao.test.normal.QueryTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.QueryTest#query_by_special_char2",
        "org.nutz.dao.test.normal.QueryTest#test_fetcy_by_fieldfilter",
        "org.nutz.dao.test.normal.QueryTest#test_query_by_fieldfilter",
        "org.nutz.dao.test.normal.QueryTest#query_by_cri_equals_null",
        "org.nutz.dao.test.normal.QueryTest#fetch_record",
        "org.nutz.dao.test.normal.QueryTest#query_by_pager",
        "org.nutz.dao.test.normal.QueryTest#query_by_special_char",
        "org.nutz.dao.test.normal.QueryTest#query_records_pager_new",
        "org.nutz.dao.test.normal.QueryTest#query_records_pager",
        "org.nutz.dao.test.normal.QueryTest#fetch_by_name",
        "org.nutz.dao.test.normal.QueryTest#query_by_like_ignorecase",
        "org.nutz.dao.test.normal.QueryTest#query_records",
        "org.nutz.dao.test.normal.QueryTest#query_by_wrap_null",
        "org.nutz.dao.test.normal.QueryTest#query_by_long_range",
        "org.nutz.dao.test.normal.QueryTest#query_by_like",
        "org.nutz.dao.test.normal.QueryTest#query_by_map_idkeyset",
        "org.nutz.dao.test.normal.QueryTest#query_by_map_namekeyset",
        "org.nutz.dao.test.normal.QueryTest#query_by_int_range",
        "org.nutz.dao.test.normal.QueryTest#test_record_to_entity",
        "org.nutz.dao.test.normal.QueryTest#query_by_orderbyset",
        "org.nutz.dao.test.normal.QueryTest#clear_by_int_range"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 42
    },
    {
      "className": "org.nutz.dao.test.normal.BoneCP_Test",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.BoneCP_Test#clear_links"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.mvc.testapp.adaptor.SimpleAdaptorTest",
      "failingMethods": [
        "org.nutz.mvc.testapp.adaptor.SimpleAdaptorTest#test_issue_543"
      ],
      "erroringMethods": [],
      "failures": [
        {
          "failureName": "java.lang.AssertionError",
          "failureDetail": "expected:\u003c1348416000000\u003e but was:\u003c1348437600000\u003e",
          "isError": false
        },
        {
          "failureName": "java.lang.AssertionError",
          "failureDetail": "expected:\u003c1348416000000\u003e but was:\u003c1348437600000\u003e",
          "isError": false
        }
      ],
      "nbFailures": 2,
      "nbErrors": 0
    },
    {
      "className": "org.nutz.dao.test.mapping.ManyManyTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.mapping.ManyManyTest#clear_links",
        "org.nutz.dao.test.mapping.ManyManyTest#fetch_links",
        "org.nutz.dao.test.mapping.ManyManyTest#delete_with",
        "org.nutz.dao.test.mapping.ManyManyTest#delete_links",
        "org.nutz.dao.test.mapping.ManyManyTest#update_links",
        "org.nutz.dao.test.mapping.ManyManyTest#update_with",
        "org.nutz.dao.test.mapping.ManyManyTest#delete_with_partly",
        "org.nutz.dao.test.mapping.ManyManyTest#delete_links_partly"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 16
    },
    {
      "className": "org.nutz.trans.SimpleTransTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.trans.SimpleTransTest#test_batch_update_rollback",
        "org.nutz.trans.SimpleTransTest#test_issue312",
        "org.nutz.trans.SimpleTransTest#test_update_rollback"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 6
    },
    {
      "className": "org.nutz.dao.test.mapping.Issue1155Test",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.mapping.Issue1155Test#test_issue_1155"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.dao.test.mapping.Issue1206Test",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.mapping.Issue1206Test#test_issue_1206"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.dao.test.mapping.DynamicManyManyTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.mapping.DynamicManyManyTest#update_links",
        "org.nutz.dao.test.mapping.DynamicManyManyTest#update_with",
        "org.nutz.dao.test.mapping.DynamicManyManyTest#delete_with",
        "org.nutz.dao.test.mapping.DynamicManyManyTest#clear_links",
        "org.nutz.dao.test.mapping.DynamicManyManyTest#delete_with_partly",
        "org.nutz.dao.test.mapping.DynamicManyManyTest#delete_links",
        "org.nutz.dao.test.mapping.DynamicManyManyTest#delete_links_partly"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 28
    },
    {
      "className": "org.nutz.dao.util.DaoUpTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.util.DaoUpTest#org.nutz.dao.util.DaoUpTest"
      ],
      "failures": [
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        },
        {
          "failureName": "java.lang.NullPointerException:",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.dao.test.mapping.RecordDaoTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.mapping.RecordDaoTest#test_insert_with_autoinc_id"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.dao.test.entity.EntityParsingTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.entity.EntityParsingTest#eval_manys",
        "org.nutz.dao.test.entity.EntityParsingTest#eval_id_name",
        "org.nutz.dao.test.entity.EntityParsingTest#test_pk_multiple",
        "org.nutz.dao.test.entity.EntityParsingTest#test_extends_tables_name",
        "org.nutz.dao.test.entity.EntityParsingTest#eval_manys_with_null_field",
        "org.nutz.dao.test.entity.EntityParsingTest#test_pk_id",
        "org.nutz.dao.test.entity.EntityParsingTest#eval_manymany",
        "org.nutz.dao.test.entity.EntityParsingTest#test_entity_with_two_id",
        "org.nutz.dao.test.entity.EntityParsingTest#test_pk_name",
        "org.nutz.dao.test.entity.EntityParsingTest#test_pk_order",
        "org.nutz.dao.test.entity.EntityParsingTest#test_complex_pojo_without_db",
        "org.nutz.dao.test.entity.EntityParsingTest#test_pk_and_name_in_same_pojo",
        "org.nutz.dao.test.entity.EntityParsingTest#test_override_field"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 26
    },
    {
      "className": "org.nutz.dao.test.normal.PkTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.PkTest#test_error_ann_name",
        "org.nutz.dao.test.normal.PkTest#test_delete_by_pks",
        "org.nutz.dao.test.normal.PkTest#test_fetch_by_pks",
        "org.nutz.dao.test.normal.PkTest#test_error_ann_id",
        "org.nutz.dao.test.normal.PkTest#test_update",
        "org.nutz.dao.test.normal.PkTest#test_fetch_by_object",
        "org.nutz.dao.test.normal.PkTest#test_delete_by_object"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 14
    },
    {
      "className": "org.nutz.dao.test.mapping.Issue338Test",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.mapping.Issue338Test#test_deleteWith_many"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.dao.test.normal.DaoRecordTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.DaoRecordTest#test_null_timestamp"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.dao.test.normal.CreateDropTableTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.CreateDropTableTest#createTableTimestampFieldDefaultNullInMySQL",
        "org.nutz.dao.test.normal.CreateDropTableTest#createDropTableInOracle"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 4
    },
    {
      "className": "org.nutz.dao.test.normal.UpdateTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.UpdateTest#batch_update_relation",
        "org.nutz.dao.test.normal.UpdateTest#test_update_ignore_null",
        "org.nutz.dao.test.normal.UpdateTest#fetch_by_name_ignorecase",
        "org.nutz.dao.test.normal.UpdateTest#test_update_obj_with_readonly_field",
        "org.nutz.dao.test.normal.UpdateTest#test_updateIgnoreNull",
        "org.nutz.dao.test.normal.UpdateTest#test_update_self_plus",
        "org.nutz.dao.test.normal.UpdateTest#testZZ",
        "org.nutz.dao.test.normal.UpdateTest#update_with_null_links",
        "org.nutz.dao.test.normal.UpdateTest#test_update_chain_and_cnd",
        "org.nutz.dao.test.normal.UpdateTest#test_update_chain_and_cnd_by_in",
        "org.nutz.dao.test.normal.UpdateTest#batch_update_partly",
        "org.nutz.dao.test.normal.UpdateTest#test_updateIgnoreNull_width_default",
        "org.nutz.dao.test.normal.UpdateTest#test_updateIgnoreNull_by_list",
        "org.nutz.dao.test.normal.UpdateTest#batch_update_all"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 28
    },
    {
      "className": "org.nutz.dao.test.normal.InsertTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.InsertTest#test_fastinsert_as_rollback",
        "org.nutz.dao.test.normal.InsertTest#test_insert_by_fieldfilter",
        "org.nutz.dao.test.normal.InsertTest#test_insert_by_el",
        "org.nutz.dao.test.normal.InsertTest#test_fastInsert_rollback_jdbc"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 8
    },
    {
      "className": "org.nutz.dao.test.normal.psql.PsqlArrayTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.psql.PsqlArrayTest#crud"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.trans.BatchTransTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.trans.BatchTransTest#try_insert_static_objects_by_many_many",
        "org.nutz.trans.BatchTransTest#try_insert_multiple_companys",
        "org.nutz.trans.BatchTransTest#try_insert_multiple_dynamic_objects"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 6
    },
    {
      "className": "org.nutz.dao.test.entity.DynamicEntityParsingTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.entity.DynamicEntityParsingTest#tank_many_many_link_test"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.dao.test.sqls.CustomizedSqlsTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.sqls.CustomizedSqlsTest#test_dynamic_insert",
        "org.nutz.dao.test.sqls.CustomizedSqlsTest#test_escape_varname_test",
        "org.nutz.dao.test.sqls.CustomizedSqlsTest#test_statice_null_field",
        "org.nutz.dao.test.sqls.CustomizedSqlsTest#test_query_without_entity",
        "org.nutz.dao.test.sqls.CustomizedSqlsTest#test_query_by_limit",
        "org.nutz.dao.test.sqls.CustomizedSqlsTest#test_issue_1176",
        "org.nutz.dao.test.sqls.CustomizedSqlsTest#test_dynamic_query",
        "org.nutz.dao.test.sqls.CustomizedSqlsTest#test_in",
        "org.nutz.dao.test.sqls.CustomizedSqlsTest#test_cnd_pager"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 18
    },
    {
      "className": "org.nutz.dao.test.normal.psql.PsqlJsonTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.psql.PsqlJsonTest#crud"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.dao.test.mapping.ManyTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.mapping.ManyTest#insert_links",
        "org.nutz.dao.test.mapping.ManyTest#update_with",
        "org.nutz.dao.test.mapping.ManyTest#fetch_null_field_links",
        "org.nutz.dao.test.mapping.ManyTest#delete_null_field_links",
        "org.nutz.dao.test.mapping.ManyTest#delete_links_partly",
        "org.nutz.dao.test.mapping.ManyTest#delete_with",
        "org.nutz.dao.test.mapping.ManyTest#delete_links",
        "org.nutz.dao.test.mapping.ManyTest#update_links",
        "org.nutz.dao.test.mapping.ManyTest#delete_with_partly",
        "org.nutz.dao.test.mapping.ManyTest#delete_null_field_links_partly",
        "org.nutz.dao.test.mapping.ManyTest#clear_null_field_links",
        "org.nutz.dao.test.mapping.ManyTest#clear_links",
        "org.nutz.dao.test.mapping.ManyTest#fetch_links"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 26
    },
    {
      "className": "org.nutz.dao.test.mapping.OneTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.mapping.OneTest#update_with",
        "org.nutz.dao.test.mapping.OneTest#clear_links_as_list",
        "org.nutz.dao.test.mapping.OneTest#update_links_as_list",
        "org.nutz.dao.test.mapping.OneTest#delete_with_as_list",
        "org.nutz.dao.test.mapping.OneTest#delete_links_as_list",
        "org.nutz.dao.test.mapping.OneTest#clear_links",
        "org.nutz.dao.test.mapping.OneTest#fetch_links",
        "org.nutz.dao.test.mapping.OneTest#update_with_as_list",
        "org.nutz.dao.test.mapping.OneTest#fetch_links_as_list",
        "org.nutz.dao.test.mapping.OneTest#update_links",
        "org.nutz.dao.test.mapping.OneTest#delete_links",
        "org.nutz.dao.test.mapping.OneTest#delete_with",
        "org.nutz.dao.test.mapping.OneTest#test_insert_with_one_id"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 26
    },
    {
      "className": "org.nutz.trans.TransactionTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.trans.TransactionTest#testNestedRollback",
        "org.nutz.trans.TransactionTest#testNestedCommit",
        "org.nutz.trans.TransactionTest#testRollback"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 6
    },
    {
      "className": "org.nutz.dao.test.sqls.CallbackTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.sqls.CallbackTest#test_fetchBooleanCallback"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.dao.test.normal.CreateTableWithCommentTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.CreateTableWithCommentTest#createTableInMySQL",
        "org.nutz.dao.test.normal.CreateTableWithCommentTest#createTableInHSQL",
        "org.nutz.dao.test.normal.CreateTableWithCommentTest#createTableInPostgersqlAndH2",
        "org.nutz.dao.test.normal.CreateTableWithCommentTest#createTableInDB2",
        "org.nutz.dao.test.normal.CreateTableWithCommentTest#createTableInOracle",
        "org.nutz.dao.test.normal.CreateTableWithCommentTest#createTableInSqlServer"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 12
    },
    {
      "className": "org.nutz.dao.test.normal.CustomizedFieldNameTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.CustomizedFieldNameTest#test_insert_update_chain_with_another_column_name"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 1
    },
    {
      "className": "org.nutz.dao.test.normal.mysql.MysqlJsonTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.mysql.MysqlJsonTest#crud"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 2
    },
    {
      "className": "org.nutz.dao.test.normal.SupportedFieldTypeTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.SupportedFieldTypeTest#insert_timestamp_field",
        "org.nutz.dao.test.normal.SupportedFieldTypeTest#check_if_support_all_normal_types",
        "org.nutz.dao.test.normal.SupportedFieldTypeTest#insert_char_field",
        "org.nutz.dao.test.normal.SupportedFieldTypeTest#check_insert_null_timestamp_field",
        "org.nutz.dao.test.normal.SupportedFieldTypeTest#check_update_sqlTimestamp",
        "org.nutz.dao.test.normal.SupportedFieldTypeTest#check_for_sqlTime"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 12
    },
    {
      "className": "org.nutz.dao.test.mapping.LinksGeneralTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.mapping.LinksGeneralTest#fetch_all_links",
        "org.nutz.dao.test.mapping.LinksGeneralTest#test_fetchLinks_cnd",
        "org.nutz.dao.test.mapping.LinksGeneralTest#insert_links_with_exception"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 6
    },
    {
      "className": "org.nutz.dao.test.normal.SimpleDaoTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.SimpleDaoTest#test_query_2",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_issue_726",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_escape_char",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_issue_928",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_sql_pager",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_delete_records",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_count_by_condition",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_fetch_null_name",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_dynamic_migration",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_get_sql",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_insert_with_id",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_integer_object_column",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_chain_insert",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_issue_1235",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_xxx",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_fetchLinks",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_insert_with",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_simple_update",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_order_by",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_fetch_by_condition_in_special_char",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_daoex_update",
        "org.nutz.dao.test.normal.SimpleDaoTest#new_nutdao_inside_trans",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_daos_ext_insert_without_null",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_count_with_entity",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_insert_special_chain",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_insert_ignore_null",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_count_groupby",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_table_exists",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_clear",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_create_error_class",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_cnd_andEX_orEX",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_record_treemap",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_delete_list",
        "org.nutz.dao.test.normal.SimpleDaoTest#run_2_sqls_with_error",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_simple_fetch_record",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_delete_null_many",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_insert_readonly",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_cnd_emtry_in",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_migration",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_insert_chain_with_null",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_bean_uuid",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_issue_1179",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_clear_two_records",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_coldefine_len",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_issue_918",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_pojo_sql_params",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_daos_queryCount",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_dao_func",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_issue_1163",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_use_blob_clob",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_issue_1166",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_varchar_BigDecimal",
        "org.nutz.dao.test.normal.SimpleDaoTest#test_issue_1168"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 106
    },
    {
      "className": "org.nutz.dao.test.sqls.SqlTemplateTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.sqls.SqlTemplateTest#testQueryForInt",
        "org.nutz.dao.test.sqls.SqlTemplateTest#testQueryEntity2",
        "org.nutz.dao.test.sqls.SqlTemplateTest#testQueryEntity1",
        "org.nutz.dao.test.sqls.SqlTemplateTest#testQueryForRecord",
        "org.nutz.dao.test.sqls.SqlTemplateTest#testUpdate",
        "org.nutz.dao.test.sqls.SqlTemplateTest#testQueryForObjectEntityOfT",
        "org.nutz.dao.test.sqls.SqlTemplateTest#testQueryForLong",
        "org.nutz.dao.test.sqls.SqlTemplateTest#testQueryForObjectClassOfT",
        "org.nutz.dao.test.sqls.SqlTemplateTest#testSqlInExp",
        "org.nutz.dao.test.sqls.SqlTemplateTest#testQueryForList",
        "org.nutz.dao.test.sqls.SqlTemplateTest#testQueryRecords",
        "org.nutz.dao.test.sqls.SqlTemplateTest#testBatchUpdate"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 24
    },
    {
      "className": "org.nutz.dao.test.smoke.BatchInsertTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.smoke.BatchInsertTest#test_insert_3_pets",
        "org.nutz.dao.test.smoke.BatchInsertTest#test_insert_2_pets_by_chain_to_map",
        "org.nutz.dao.test.smoke.BatchInsertTest#test_fast_insert_2_pets_by_chain_to_map"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 6
    },
    {
      "className": "org.nutz.dao.test.normal.AutoGenerateValueTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.test.normal.AutoGenerateValueTest#test_simple",
        "org.nutz.dao.test.normal.AutoGenerateValueTest#test_var_in_prev"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 4
    },
    {
      "className": "org.nutz.dao.texp.ChainTest",
      "failingMethods": [],
      "erroringMethods": [
        "org.nutz.dao.texp.ChainTest#test_chain_to_object",
        "org.nutz.dao.texp.ChainTest#test_chain_from_map",
        "org.nutz.dao.texp.ChainTest#test_chain_from_object"
      ],
      "failures": [
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        },
        {
          "failureName": "org.nutz.ioc.IocException",
          "failureDetail": "IocBean[dao -\u003e dataSource] throw Exception when creating",
          "isError": true
        }
      ],
      "nbFailures": 0,
      "nbErrors": 6
    }
  ],
  "bugRepo": "nutzam/nutz"
}